In [139]:
import torch
import math
class LSTM:
    def __init__(self, size):
        size = 3
        self.describe = {}
        
        #params
        self.W = torch.rand(size, requires_grad=True)
        self.Wi = torch.rand(size, requires_grad=True)
        self.Wo = torch.rand(size, requires_grad=True)
        self.Wf = torch.rand(size, requires_grad=True)

        self.U = torch.rand(size, requires_grad=True)
        self.Ui = torch.rand(size, requires_grad=True)
        self.Uo = torch.rand(size, requires_grad=True)
        self.Uf = torch.rand(size, requires_grad=True)

        self.b = torch.rand(size, requires_grad=True)
        self.bi = torch.rand(size, requires_grad=True)
        self.bo = torch.rand(size, requires_grad=True)
        self.bf = torch.rand(size, requires_grad=True)
        
        #states
        self.ht = torch.rand(size)
        self.st = torch.rand(size)
        self.Tst = torch.rand(size)
        
        # gates 
        self.It = torch.rand(size)
        self.Ft = torch.rand(size)
        self.Ot = torch.rand(size)
        
        return 
    
    def params(self):
        self.describe['ht'] = self.ht
        self.describe['st'] = self.st
        self.describe['W'] = self.W
        self.describe['U'] = self.U
        self.describe['b'] = self.b
        
        self.describe['Wi'] = self.Wi
        self.describe['Ui'] = self.Ui
        self.describe['bi'] = self.bi
        
        self.describe['Wf'] = self.Wf
        self.describe['Uf'] = self.Uf
        self.describe['bf'] = self.bf
        
        self.describe['Wo'] = self.Wo
        self.describe['Uo'] = self.Uo
        self.describe['bo'] = self.bo
        
        self.describe['It'] = self.It
        self.describe['Ft'] = self.Ft
        self.describe['Ot'] = self.Ot
        self.describe['Tst'] = self.Tst
        return self.describe
    
    def sigmoid(self,x):
        return 1 / (1 + math.exp(-x))
    
    def actFunction(self, x):
        return torch.sigmoid(x) 
    
    def apply(self, xt):
        actFunction = self.actFunction
        #Input gate
        self.It = actFunction(self.Wi * self.ht + self.Ui * xt + self.bi)
        #Forget gate
        self.Ft = actFunction(self.Wf * self.ht + self.Uf * xt + self.bf)
        #output gate
        self.Ot = actFunction(self.Wo * self.ht + self.Uo * xt + self.bo)
        
        #temporary state tst
        self.Tst = actFunction(self.W * self.ht + self.U * xt + self.b)
        #cell state
        self.st = self.Ft * self.st + self.It * self.Tst
        # hidden state
        self.ht = self.Ot * actFunction(self.st)
        return self.ht

    
def train():
    for input, target in dataset:
        optimizer.zero_grad()
        output = model(input)
        loss = loss_fn(output, target)
        loss.backward()
        optimizer.step()

    
model = LSTM(3)
xt = torch.tensor([1,2,3])
y = model.apply(xt)

print(y)
#model.params()

y[0].backward()
model.W.grad

tensor([0.7041, 0.5777, 0.7175], grad_fn=<MulBackward0>)


tensor([0.0086, 0.0000, 0.0000])

In [133]:
a = torch.tensor(1., requires_grad = True)
b = torch.tensor(3., requires_grad = True)
#x = a*b
c = torch.tensor(4.)
x = c *a*b
x.backward()
a.grad

tensor(12.)

In [109]:
import numpy as np
import math
class LSTM:
    def __init__(self, size):
        size = 3
        self.describe = {}
        self.ht = np.random.rand(size)
        self.st = np.random.rand(size)

        self.W = np.random.rand(size)
        self.Wi = np.random.rand(size)
        self.Wo = np.random.rand(size)
        self.Wf = np.random.rand(size)

        self.U = np.random.rand(size)
        self.Ui = np.random.rand(size)
        self.Uo = np.random.rand(size)
        self.Uf = np.random.rand(size)

        self.b = np.random.rand(size)
        self.bi = np.random.rand(size)
        self.bo = np.random.rand(size)
        self.bf = np.random.rand(size)
        
        self.It = np.random.rand(size)
        self.Ft = np.random.rand(size)
        self.Ot = np.random.rand(size)
        self.Tst = np.random.rand(size)
        return 
    
    def params(self):
        self.describe['ht'] = self.ht
        self.describe['st'] = self.st
        self.describe['W'] = self.W
        self.describe['U'] = self.U
        self.describe['b'] = self.b
        
        self.describe['Wi'] = self.Wi
        self.describe['Ui'] = self.Ui
        self.describe['bi'] = self.bi
        
        self.describe['Wf'] = self.Wf
        self.describe['Uf'] = self.Uf
        self.describe['bf'] = self.bf
        
        self.describe['Wo'] = self.Wo
        self.describe['Uo'] = self.Uo
        self.describe['bo'] = self.bo
        
        self.describe['It'] = self.It
        self.describe['Ft'] = self.Ft
        self.describe['Ot'] = self.Ot
        self.describe['Tst'] = self.Tst
        return self.describe
    
    def sigmoid(self,x):
        return 1 / (1 + math.exp(-x))
    
    def actFunction(self, x):
        #print(x)
        li = [self.sigmoid(x[i]) for i in range(x.size)]
        
        return np.array(li) 
    
    def apply(self, xt):
        actFunction = self.actFunction
        #Input gate
        self.It = actFunction(self.Wi * self.ht + self.Ui * xt + self.bi)
        #Forget gate
        self.Ft = actFunction(self.Wf * self.ht + self.Uf * xt + self.bf)
        #output gate
        self.Ot = actFunction(self.Wo * self.ht + self.Uo * xt + self.bo)
        
        #temporary state tst
        self.TSt = actFunction(self.W * self.ht + self.U * xt + self.b)
        #cell state
        self.st = self.Ft * self.st + self.It * self.Tst
        # hidden state
        self.ht = self.Ot * actFunction(self.st)
        return self.ht
    
    
    
model = LSTM(3)
model.params()  

{'ht': array([0.39242422, 0.26381669, 0.27738256]),
 'st': array([0.05358252, 0.77886007, 0.91576527]),
 'W': array([0.62315329, 0.73418029, 0.0743484 ]),
 'U': array([0.43302254, 0.66950187, 0.36207133]),
 'b': array([0.39992735, 0.89464313, 0.40140242]),
 'Wi': array([0.82979774, 0.00147245, 0.532249  ]),
 'Ui': array([0.51131341, 0.85532833, 0.40716028]),
 'bi': array([0.34478829, 0.57475852, 0.67099443]),
 'Wf': array([0.74301602, 0.51447308, 0.74847522]),
 'Uf': array([0.62047713, 0.03544008, 0.73678152]),
 'bf': array([0.89479618, 0.14301349, 0.81211241]),
 'Wo': array([0.33421242, 0.56399332, 0.8585902 ]),
 'Uo': array([0.0037347 , 0.46843093, 0.7853012 ]),
 'bo': array([0.04038124, 0.02546341, 0.21273289]),
 'It': array([0.78081928, 0.84098572, 0.77660704]),
 'Ft': array([0.36593455, 0.76527385, 0.47994283]),
 'Ot': array([0.57937577, 0.79798225, 0.40323391]),
 'Tst': array([0.0671276 , 0.69922624, 0.44708639])}

In [110]:
x = model.apply([1,2,4])
x

array([0.28508099, 0.5632485 , 0.76644345])

In [111]:
model.params()

{'ht': array([0.28508099, 0.5632485 , 0.76644345]),
 'st': array([0.09739639, 1.09150506, 1.31023052]),
 'W': array([0.62315329, 0.73418029, 0.0743484 ]),
 'U': array([0.43302254, 0.66950187, 0.36207133]),
 'b': array([0.39992735, 0.89464313, 0.40140242]),
 'Wi': array([0.82979774, 0.00147245, 0.532249  ]),
 'Ui': array([0.51131341, 0.85532833, 0.40716028]),
 'bi': array([0.34478829, 0.57475852, 0.67099443]),
 'Wf': array([0.74301602, 0.51447308, 0.74847522]),
 'Uf': array([0.62047713, 0.03544008, 0.73678152]),
 'bf': array([0.89479618, 0.14301349, 0.81211241]),
 'Wo': array([0.33421242, 0.56399332, 0.8585902 ]),
 'Uo': array([0.0037347 , 0.46843093, 0.7853012 ]),
 'bo': array([0.04038124, 0.02546341, 0.21273289]),
 'It': array([0.76525952, 0.90769446, 0.92036174]),
 'Ft': array([0.85898083, 0.58652548, 0.98141886]),
 'Ot': array([0.54370542, 0.75233713, 0.9731976 ]),
 'Tst': array([0.0671276 , 0.69922624, 0.44708639])}

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)
input_dim = 10
hidden_dim = 10
lstm = nn.LSTM(input_dim, hidden_dim)


inputs = [torch.randn(1, 10) for _ in range(5)]  # make a sequence of length 5
#print(inputs)
# initialize the hidden state.
hidden = (torch.randn(1, 1, 10),
          torch.randn(1, 1, 10))

for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    out, hidden = lstm(i.view(1, 1, -1), hidden)
    
print(hidden)

RuntimeError: lstm expects two hidden states

In [9]:
model = nn.Sequential(
          nn.Conv2d(1,20,5),
          nn.ReLU(),
          nn.Conv2d(20,64,5),
          nn.ReLU()
        )
