In [3]:
import torch
import torch.nn as nn

ModuleNotFoundError: No module named 'torch'

In [147]:
model = nn.Sequential(nn.Conv2d(3,24,(5,5),(2,2)),
                      nn.ReLU(),
                      nn.Conv2d(24,36,(5,5),(2,2)),
                      nn.ReLU(),
                      nn.Conv2d(36,48,(5,5),(2,2)),
                      nn.ReLU(),
                      nn.Conv2d(48,64,(3,3),(1,1)),
                      nn.ReLU(),
                      nn.Conv2d(64,64,(3,3),(1,1)),
                      nn.ReLU(),
                      nn.Flatten(),
                      nn.Linear(1152,1),
                      nn.ReLU()
                     )

loss_fn = torch.nn.MSELoss(reduction='sum')
learning_rate = 1e-1
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


x = torch.rand((100, 3, 66, 200))
y = torch.rand(100,1)
print(model(x[:1]))

for t in range(10):
    y_pred = model(x[:(t+1)*10])
    loss = loss_fn(y_pred, y[:(t+1)*10])
    print(y_pred[0], loss.item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

tensor([[0.0180]], grad_fn=<ReluBackward0>)
tensor([0.0180], grad_fn=<SelectBackward>) 2.260197401046753
tensor([30606780.], grad_fn=<SelectBackward>) 1.8965776715218944e+16
tensor([0.], grad_fn=<SelectBackward>) 6.881675720214844
tensor([0.], grad_fn=<SelectBackward>) 10.351865768432617
tensor([0.], grad_fn=<SelectBackward>) 11.175758361816406
tensor([0.], grad_fn=<SelectBackward>) 13.313314437866211
tensor([0.], grad_fn=<SelectBackward>) 15.420353889465332
tensor([0.], grad_fn=<SelectBackward>) 17.45132064819336
tensor([0.], grad_fn=<SelectBackward>) 20.30356216430664
tensor([0.], grad_fn=<SelectBackward>) 24.08241081237793


In [1]:
loss_fn = torch.nn.MSELoss(reduction = 'sum')
learning_rate = 1e-1
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

CNNmodel = nn.Sequential(nn.Conv2d(3,24,(5,5),(2,2)),
                      nn.ReLU(),
                      nn.Conv2d(24,36,(5,5),(2,2)),
                      nn.ReLU(),
                      nn.Conv2d(36,48,(5,5),(2,2)),
                      nn.ReLU(),
                      nn.Conv2d(48,64,(3,3),(1,1)),
                      nn.ReLU(),
                      nn.Conv2d(64,64,(3,3),(1,1)),
                      nn.ReLU(),
                      nn.Flatten() )

FCNNmodel = nn.Sequential(nn.Linear(1164, 100),
                         nn.ReLU(),
                         nn.Linear(100, 50),
                         nn.ReLU(),
                         nn.Linear(50, 10),
                         nn.ReLU(),
                         nn.Linear(10, 1),
                         nn.ReLU()
                         )
LSTMmodel = nn.LSTM( 1152, 1164, 3, batch_first = True)
hn = torch.randn(3, 1, 1164)
cn = torch.randn(3, 1, 1164)
LSTMmodel(torch.rand((1,1,1152)), (hn, cn))


y_pred = []
x = torch.rand((100, 3, 66, 200))
y = torch.rand(10)
print(y)
for j in range(10):
    y_pred = []
    for i in range(10):
        x_ = x[i].view(1,3, 66, 200)
        x_ = CNNmodel(x_).view((1,1,1152))
        x_, (hn, cn) = LSTMmodel(x_)
        y_pred.append(FCNNmodel(x_.view(1164)))
        #print(y_pred[i])
    
    loss = loss_fn(torch.tensor(y_pred, requires_grad = True), y )
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
print(y,y_pred)

NameError: name 'torch' is not defined

In [160]:
rnn = nn.LSTM(1152, 1164, 3)

input = torch.randn(1, 10, 1152)
h0 = torch.randn(3, 10, 1164)
c0 = torch.randn(3, 10, 1164)
output, (hn, cn) = rnn(input, (h0, c0))
output

tensor([[[ 0.1324, -0.1962, -0.1969,  ..., -0.0797,  0.1958, -0.0449],
         [-0.1257,  0.3401,  0.0651,  ...,  0.5061,  0.1147, -0.6397],
         [ 0.0867, -0.0460, -0.0064,  ...,  0.2911, -0.0369, -0.0088],
         ...,
         [-0.1485,  0.3546, -0.0603,  ..., -0.4456,  0.5361, -0.1769],
         [ 0.5419,  0.0600,  0.0106,  ..., -0.2108, -0.0815, -0.1012],
         [ 0.4541, -0.0733, -0.0405,  ..., -0.1643, -0.5368, -0.3579]]],
       grad_fn=<StackBackward>)

In [157]:
rnn = nn.LSTM(10, 20, 2)
input = torch.randn(1, 3, 10)
h0 = torch.randn(2, 3, 20)
c0 = torch.randn(2, 3, 20)
output, (hn, cn) = rnn(input, (h0, c0))
output.shape

torch.Size([1, 3, 20])

In [212]:
torch.rand((1,1,1152))

tensor([[[0.6549, 0.1065, 0.6089,  ..., 0.2321, 0.8988, 0.9177]]])